# Generated by Django 2.2.11 on 2020-03-23 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todonode',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='todonode',
            name='content',
            field=models.CharField(max_length=130),
        ),
    ]
