# Generated by Django 2.2.11 on 2020-03-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200323_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todonode',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
