# Generated by Django 2.2.11 on 2020-03-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200324_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todonode',
            name='due_date',
        ),
    ]
