# Generated by Django 2.2.11 on 2020-03-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todonode_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todonode',
            old_name='content',
            new_name='todo',
        ),
    ]
