# Generated by Django 2.2.11 on 2020-03-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200324_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='todonode',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
