# Generated by Django 2.2.11 on 2020-03-27 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todonode_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='todonode',
            name='comment',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='todonode',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='todonode',
            name='todo',
            field=models.CharField(max_length=100),
        ),
    ]
