# Generated by Django 2.2.11 on 2020-04-01 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20200327_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todonode',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='todonode',
            name='due_date',
        ),
        migrations.AddField(
            model_name='todonode',
            name='percents_done',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
