# Generated by Django 2.2.11 on 2020-04-01 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20200401_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='todonode',
            name='due_date',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
    ]
