# Generated by Django 2.2.11 on 2020-04-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_todonode_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todonode',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='todonode',
            name='percents_done',
        ),
    ]
