# Generated by Django 2.2.11 on 2020-04-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_todonode_percents_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todonode',
            name='percents_done',
        ),
    ]
